/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tdg.mexicanos;

import java.awt.Button;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emanu
 */
public class Control extends javax.swing.JPanel {
    String equipoJugador = "1";
    Button tachar;
    private JTable tablaControl;
    private DefaultTableModel modeloTablaControl;
    private Tablero tablero;

    /**
     * Creates new form Control
     */
    public Control(Tablero tablero) {
        initComponents();
        this.tablero = tablero;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int width = (int) screenSize.getWidth();
        int height = (int) screenSize.getHeight();
        this.setSize(width, height);
        this.setBackground(new java.awt.Color(61, 61, 61));
        
        // Crear la tabla editable con columnas "Respuesta" y "Puntos"
        modeloTablaControl = new DefaultTableModel(new Object[] { "RESPUESTAS", "PUNTOS" }, 8) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return true;
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 1) {
                    return Integer.class;
                }
                return String.class;
            }
        };

        innitTabla();

        tablaControl = new JTable(modeloTablaControl);
        tablaControl.setFont(new java.awt.Font("Tahoma", 0, 20));
        tablaControl.setRowHeight(30);

        JScrollPane scrollPane = new JScrollPane(tablaControl);
        int tableWidth = 700;
        scrollPane.setBounds((getWidth() - tableWidth) / 2, 50, tableWidth, 270);
        add(scrollPane);

        // Botón para enviar datos al Tablero
        JButton btnEnviar = new JButton("Enviar al Tablero");
        btnEnviar.setBounds(width/2-100, 400, 200, 50);
        btnEnviar.addActionListener(obtenerDatos());
        add(btnEnviar);

        setVisible(true);

    }

    public ActionListener obtenerDatos(){
        return e->{
            innitTabla();
        };
    }

    public void innitTabla(){
        int rowCount = modeloTablaControl.getRowCount();
            Object[][] datos = new Object[rowCount][2];
            for (int i = 0; i < rowCount; i++) {
                datos[i][0] = modeloTablaControl.getValueAt(i, 0);
                datos[i][1] = modeloTablaControl.getValueAt(i, 1);
            }
            // Enviar datos al Tablero
            tablero.actualizarTabla(datos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
